ascent:
  resource: ../../src/Controller/AscentController.php
  type: annotation
  prefix: /api/{location}/

boulder:
  resource: ../../src/Controller/BoulderController.php
  type: annotation
  prefix: /api/{location}/

grade:
  resource: ../../src/Controller/GradeController.php
  type: annotation
  prefix: /api/{location}/

holdStyle:
  resource: ../../src/Controller/HoldStyleController.php
  type: annotation
  prefix: /api/{location}/

ranking:
  resource: ../../src/Controller/RankingController.php
  type: annotation
  prefix: /api/{location}/

tag:
  resource: ../../src/Controller/BoulderTagController.php
  type: annotation
  prefix: /api/{location}/

wall:
  resource: ../../src/Controller/WallController.php
  type: annotation
  prefix: /api/{location}/

boulderError:
  resource: ../../src/Controller/BoulderErrorController.php
  type: annotation
  prefix: /api/{location}/

boulderDoubt:
  resource: ../../src/Controller/AscentDoubtController.php
  type: annotation
  prefix: /api/{location}/

boulderLabel:
  resource: ../../src/Controller/LabelController.php
  type: annotation
  prefix: /api/{location}/

setter:
  resource: ../../src/Controller/SetterController.php
  type: annotation
  prefix: /api/{location}/

user:
  resource: ../../src/Controller/UserController.php
  type: annotation
  prefix: /api

global:
  resource: ../../src/Controller/GlobalController.php
  type: annotation
  prefix: /api

token:
  resource: ../../src/Controller/TokenController.php
  type: annotation
  prefix: /api

compare:
  resource: ../../src/Controller/CompareController.php
  type: annotation
  prefix: /api/{location}/

schedule:
  resource: ../../src/Controller/ScheduleController.php
  type: annotation
  prefix: /api/{location}/

reservation:
  resource: ../../src/Controller/ReservationController.php
  type: annotation
  prefix: /api/{location}/

room:
  resource: ../../src/Controller/RoomController.php
  type: annotation
  prefix: /api/{location}/

time_slot:
  resource: ../../src/Controller/TimeSlotController.php
  type: annotation
  prefix: /api/{location}/

time_slot_exclusion:
  resource: ../../src/Controller/TimeSlotExclusionController.php
  type: annotation
  prefix: /api/{location}/

comment:
  resource: ../../src/Controller/BoulderCommentController.php
  type: annotation
  prefix: /api/{location}/

rating:
  resource: ../../src/Controller/BoulderRatingController.php
  type: annotation
  prefix: /api/{location}/